version: "3"
services:
  nsdc_service:
    build:
      context: ./
    ports:
      - "3000:3000"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=nsdc
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"